"""add marks field to question

Revision ID: 644eee7e592e
Revises: ae7ecaf7e84f
Create Date: 2025-10-19 14:27:51.675437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644eee7e592e'
down_revision: Union[str, Sequence[str], None] = 'ae7ecaf7e84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('marks', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'marks')
    # ### end Alembic commands ###
