"""add correct_answer column to questions

Revision ID: ae7ecaf7e84f
Revises: 79420480f904
Create Date: 2025-10-19 13:51:18.975986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7ecaf7e84f'
down_revision: Union[str, Sequence[str], None] = '79420480f904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer')
    # ### end Alembic commands ###
