"""Add grading_rules to exams table

Revision ID: e9e166f6bdec
Revises: 313f075c250e
Create Date: 2025-10-11 17:17:48.022324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e166f6bdec'
down_revision: Union[str, Sequence[str], None] = '313f075c250e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('grading_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'grading_rules')
    # ### end Alembic commands ###
